import React, { useState } from 'react'
import { ArrowUpRight, Bell, HandCoins, Layers3, ListOrdered, Plus, Rocket, Star, Vault, WalletCards } from 'lucide-react'
import { Badge, Button, Metric, PageTabs, Panel, SegmentedControl, WorkspaceHeader } from '../design-system/index.jsx'
import ActionDialog from '../components/ActionDialog.jsx'

const positions = [
  { id: '8420', pair: 'ETH / USDC', model: 'Dynamic liquidity', protocol: 'ALMM', value: '$8,420.36', fees: '$182.40', range: 'Active range', status: 'In range' },
  { id: '4431', pair: 'GIWA / USDC', model: 'Range liquidity', protocol: 'ARL', value: '$4,420.16', fees: '$101.80', range: '$0.84 – $1.62', status: 'In range' },
]

export default function PortfolioPage({ connected, setConnected, navigate }) {
  const [section, setSection] = useState('Liquidity')
  const [view, setView] = useState('Positions')
  const [dialog, setDialog] = useState(null)
  return <>
    <WorkspaceHeader title="Portfolio" actions={<Button onClick={() => navigate('create')} icon={<Plus size={18} />}>Add liquidity</Button>} meta={connected ? <Badge tone="success">0x8F2…91A</Badge> : null} />
    {connected && <div className="metrics-grid four"><Metric label="Portfolio value" value="$12,840.52" note="+$284.20 earned" tone="positive" /><Metric label="Claimable" value="$284.20" note="Fees and rewards" /><Metric label="Open positions" value="2" note="Both in range" tone="positive" /><Metric label="Open orders" value="1" note="62% filled" /></div>}
    <PageTabs items={['Liquidity', 'Revenue', 'Saved & alerts', 'Creator']} value={section} onChange={setSection} label="Portfolio workspace" />
    <Panel className="portfolio-panel">{!connected ? <div className="empty-state portfolio-connect-state"><WalletCards size={28} /><strong>Connect wallet to open your portfolio</strong><p>Positions, orders, rewards, revenue, and alerts will appear here.</p><Button onClick={() => setConnected(true)}>Connect wallet</Button></div> : section === 'Liquidity' ? <><div className="panel-title-row"><h2 className="type-h3">Positions and orders</h2><SegmentedControl items={['Positions', 'Limit orders', 'Activity']} value={view} onChange={setView} label="Portfolio view" /></div>{view === 'Positions' && <div className="position-list">{positions.map((position) => <article key={position.id} onClick={() => navigate(`position/${position.id}`)}><div className="position-name"><span><Layers3 size={20} /></span><div><strong>{position.pair}</strong><small>{position.model} · Powered by {position.protocol}</small></div></div><div><span>Position value</span><strong>{position.value}</strong></div><div><span>Claimable fees</span><strong className="positive-value">{position.fees}</strong></div><div><span>Range</span><strong>{position.range}</strong></div><Badge tone="success">{position.status}</Badge><button aria-label="Open position"><ArrowUpRight size={19} /></button></article>)}</div>}{view === 'Limit orders' && <div className="order-list"><article><ListOrdered size={20} /><div><strong>Sell ETH</strong><small>ETH / USDC · target $4,760</small></div><div><span>Filled</span><strong>62%</strong></div><div><span>Claimable</span><strong>2,948.20 USDC</strong></div><Button size="sm" variant="secondary" onClick={() => setDialog('Manage limit order')}>Manage</Button></article></div>}{view === 'Activity' && <div className="timeline-list"><article><HandCoins size={18} /><div><strong>Fees accrued</strong><span>+$42.80 USDC</span></div><time>Today</time></article><article><Plus size={18} /><div><strong>Liquidity added</strong><span>ETH / USDC</span></div><time>Sep 2</time></article></div>}</> : section === 'Revenue' ? <RevenueWorkspace navigate={navigate} setDialog={setDialog} /> : section === 'Saved & alerts' ? <SavedAlerts navigate={navigate} /> : <CreatorWorkspace navigate={navigate} />}</Panel>
    {dialog && <ActionDialog title={dialog} rows={[["Wallet", "0x8F2…91A"], ["Available", "$284.20"], ["Destination", "Connected wallet"]]} action="Review action" onClose={() => setDialog(null)} />}
  </>
}

function RevenueWorkspace({ navigate, setDialog }) { return <div className="portfolio-subspace"><div className="subspace-metrics"><Metric label="Claimable now" value="$203.20" note="3 sources" tone="positive" /><Metric label="Lifetime gross" value="$2,418.60" /><Metric label="Lifetime claimed" value="$1,842.60" /></div><div className="context-actions"><article><HandCoins /><div><strong>Creator revenue</strong><span>NOVA launch · 82.4 GIWA</span></div><Button size="sm" variant="secondary" onClick={() => setDialog('Claim creator revenue')}>Claim</Button></article><article><Vault /><div><strong>Shared fee vault</strong><span>ETH / USDC partner vault</span></div><Button size="sm" variant="secondary" onClick={() => navigate('fees')}>Manage vault</Button></article><article><HandCoins /><div><strong>Referral revenue</strong><span>3 attributed routes · 74.80 USDC</span></div><Button size="sm" variant="secondary" onClick={() => setDialog('Claim referral revenue')}>Claim</Button></article></div></div> }
function SavedAlerts({ navigate }) { return <div className="context-actions"><article><Star /><div><strong>ETH / USDC</strong><span>Saved pool · Dynamic liquidity</span></div><Button size="sm" variant="secondary" onClick={() => navigate('pool/eth-usdc')}>Open</Button></article><article><Bell /><div><strong>Price above $4,760</strong><span>ETH / USDC · In-app + Email</span></div><Badge tone="success">Armed</Badge></article><article><Bell /><div><strong>Swap larger than $50K</strong><span>GIWA / USDC · In-app</span></div><Badge tone="neutral">Triggered</Badge></article></div> }
function CreatorWorkspace({ navigate }) { return <div className="context-actions"><article><Rocket /><div><strong>ETH / GIWA launch</strong><span>Trading · 68% funded</span></div><Button size="sm" variant="secondary" onClick={() => navigate('launch/eth')}>Open launch</Button></article><article><Layers3 /><div><strong>ETH / USDC pool</strong><span>Scheduled pool · Active</span></div><Button size="sm" variant="secondary" onClick={() => navigate('pool/eth-usdc')}>Manage liquidity</Button></article><article><Vault /><div><strong>Partner fee vault</strong><span>2 recipients · 284.20 USDC funded</span></div><Button size="sm" variant="secondary" onClick={() => navigate('fees')}>Funding & claims</Button></article></div> }
